// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noadujvmcjzsyxbtaizp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vYWR1anZtY2p6c3l4YnRhaXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzYxMTAsImV4cCI6MjA2MDgxMjExMH0.3HSFq6G5g0mTdvKBtcREOmYtRsg8bmeDvGDc3GVKxMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);